{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-compose/0.25.0/resources-compose-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-compose",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose.klib",
          "url": "resources-compose-macosarm64-0.25.0.klib",
          "size": 25704,
          "sha512": "fd4fc336e2dcd4a944e55e25de852e60f2ebf07684eb09e28fd125656d9cf04c17bc5d9a44addaf9502652ecd2765d5ce3e16998b8514cc8161827a1f4079c39",
          "sha256": "56dd7219937972791df8019738623c372120f726d0aed3bd25d7fd0be197e2ed",
          "sha1": "433ceb39133ffd3d00d47ba8704e8371a9ebb09d",
          "md5": "dda879126a1a90e197ccc58e64f976a2"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-compose-macosarm64-0.25.0-sources.jar",
          "url": "resources-compose-macosarm64-0.25.0-sources.jar",
          "size": 12092,
          "sha512": "eda884bb8cc173d9d5650ce532422f8b835735ba561b1e4a40697d63e7a97ba2f21793cdb028f9dee816801a5430a8d32949788909d8cd7f47e3db2e4f257dab",
          "sha256": "20e9b36eb51bba6032692f820a666ec79200e33ac9938dc56946e49d52592cf7",
          "sha1": "c4f8cb1d9a4e8796e5c2ca67d6dc201716d23842",
          "md5": "e6d04df6c3a7cbafd8aad6cbe59e7cce"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-macosarm64-0.25.0-metadata.jar",
          "url": "resources-compose-macosarm64-0.25.0-metadata.jar",
          "size": 14471,
          "sha512": "f804b5745668390612b785d40c61ab06c3088308bb06576f3e2061c4a18dbb99f925807cc217befe449fab02d53656c30d885d9451fe3b5e8615e578f1dce9e1",
          "sha256": "8fe4b7f3ec952dbfe567bd85a20b9414a6b67a426e3818ccd9a7e30d84d4f8a7",
          "sha1": "d44004e097f615d5f6e3dfafbab90b728e01ac95",
          "md5": "f6bd459f0999adc2956bdef90afb7a7b"
        }
      ]
    }
  ]
}
