{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.icerock.moko",
    "module": "resources",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-metadata-0.25.0.jar",
          "url": "resources-0.25.0.jar",
          "size": 9643,
          "sha512": "5472ef3f923c5eea83335163121b1e08c2ca13320250ce2f55a594cbf22cc30253ad22f9918788a9dce59c8b280958f003fd204e6f405c0310da3e37ad526d4d",
          "sha256": "b6d14fc772cf8687688532bfa5e72ec3d2ce5fd00c64b97562b7dd37481832f9",
          "sha1": "aaf73e33d16a8edbe5f5ebe01cb17a3aa00fea70",
          "md5": "61639f251d64d786e8afa843004ee6aa"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resources-kotlin-0.25.0-sources.jar",
          "url": "resources-0.25.0-sources.jar",
          "size": 36677,
          "sha512": "b578e4539fe6836e7fa8a4f91d2063d11f3fb0f1bc2ec3a2d2a984bcce7cceae0669976e2060e9c1a412e1151fe81dd3a4887cc508df77fd4f2c33adfc3a9edf",
          "sha256": "5e4491be9049489d4160003827eb81e42815a70647659e5a8e3705f5c912cbcc",
          "sha1": "d2ec08b1c3ad19389ccce2d43c56d1cd2d6f1c94",
          "md5": "22cf5863487e291ee2ca5463e8f2ff15"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-android/0.25.0/resources-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-android/0.25.0/resources-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-android/0.25.0/resources-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-android/0.25.0/resources-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-android/0.25.0/resources-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-android/0.25.0/resources-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iosarm64/0.25.0/resources-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iosarm64/0.25.0/resources-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iosarm64/0.25.0/resources-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iossimulatorarm64/0.25.0/resources-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iossimulatorarm64/0.25.0/resources-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iossimulatorarm64/0.25.0/resources-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iosx64/0.25.0/resources-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iosx64/0.25.0/resources-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-iosx64/0.25.0/resources-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-js/0.25.0/resources-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-js/0.25.0/resources-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-js/0.25.0/resources-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-jvm/0.25.0/resources-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-jvm/0.25.0/resources-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-jvm/0.25.0/resources-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-macosarm64/0.25.0/resources-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-macosarm64/0.25.0/resources-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-macosarm64/0.25.0/resources-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-macosx64/0.25.0/resources-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-macosx64/0.25.0/resources-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-macosx64/0.25.0/resources-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosarm32/0.25.0/resources-watchosarm32-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosarm32",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosarm32/0.25.0/resources-watchosarm32-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosarm32",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosarm32/0.25.0/resources-watchosarm32-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosarm32",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosarm64/0.25.0/resources-watchosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosarm64/0.25.0/resources-watchosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosarm64/0.25.0/resources-watchosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchossimulatorarm64/0.25.0/resources-watchossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchossimulatorarm64/0.25.0/resources-watchossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchossimulatorarm64/0.25.0/resources-watchossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosx64/0.25.0/resources-watchosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosx64/0.25.0/resources-watchosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-watchosx64/0.25.0/resources-watchosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-watchosx64",
        "version": "0.25.0"
      }
    }
  ]
}
