{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-compose/0.25.0/resources-compose-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-compose",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose.klib",
          "url": "resources-compose-iossimulatorarm64-0.25.0.klib",
          "size": 25810,
          "sha512": "cc5a6477e21e85c3ebc9ea5382e1a43e015186ac0ca9d10a2e5da68dbe84852548d26cefe8c1f2f463a4ca7d825ac3418252ccc26a1b990657dac771437afe49",
          "sha256": "6114f187c5daf1f2862efe69518c6c292c9ea5a4b4da5b93b43cfd841206490c",
          "sha1": "bfa075961863d4386578b29fe8525b866391c2dc",
          "md5": "bcbaed277c7f34c639bc81bd3641359a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-compose-iossimulatorarm64-0.25.0-sources.jar",
          "url": "resources-compose-iossimulatorarm64-0.25.0-sources.jar",
          "size": 12081,
          "sha512": "4d5a75862a17898f620afa8d68cf447af1a8294a5cdad563f9a454aa7264e8113c2e665410c1f3df176593e6f17a2cfb3ed67497a99276c6c729b0f5ceeb2097",
          "sha256": "e553ec1c09fe77ea067942d760bbf7c90d71e4cd03107b1b5a5b1c14cd8297d6",
          "sha1": "4a1b30239aaee10900260a229a88997666d6b666",
          "md5": "dc64b2bbd27a4f8ac2f98b4eca39eb2e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-iossimulatorarm64-0.25.0-metadata.jar",
          "url": "resources-compose-iossimulatorarm64-0.25.0-metadata.jar",
          "size": 14343,
          "sha512": "ebbdc3ef712e14b3b22e7df6f40ccf7674a34c7c598b3f8072d67b35988ffbb440ffbb0512c9898be891d358cdcbc178f32e0c3fa03c89a34b054894ba58acba",
          "sha256": "c869f8610be6f329b54a097f490e4d0b72f00211fb85c0c2da5fd2967b2ecc1f",
          "sha1": "2689c7c465feb844b5f43d8aa6ddab9943cf289a",
          "md5": "4b2c1d4b5456716ad20385fcfce9e1cf"
        }
      ]
    }
  ]
}
