{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-compose/0.25.0/resources-compose-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-compose",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose.klib",
          "url": "resources-compose-iosx64-0.25.0.klib",
          "size": 25707,
          "sha512": "5e66ee45db7a2aea2cd451934cd387cf40b25bb1fe4aa987a5812ce418c99917ca433ce772c7d8a800f7285a4b993ac2dc510f5c1a1706ffeae7750e068d07d2",
          "sha256": "583bdb494bbce67bad53d41deb831d0dddfbe622525404123b686568b5c79338",
          "sha1": "d3d97e3b46332237aea19c17b66b100e5f87f0ca",
          "md5": "afc83a5f522f4eea52c7163c779af453"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-compose-iosx64-0.25.0-sources.jar",
          "url": "resources-compose-iosx64-0.25.0-sources.jar",
          "size": 12081,
          "sha512": "4d5a75862a17898f620afa8d68cf447af1a8294a5cdad563f9a454aa7264e8113c2e665410c1f3df176593e6f17a2cfb3ed67497a99276c6c729b0f5ceeb2097",
          "sha256": "e553ec1c09fe77ea067942d760bbf7c90d71e4cd03107b1b5a5b1c14cd8297d6",
          "sha1": "4a1b30239aaee10900260a229a88997666d6b666",
          "md5": "dc64b2bbd27a4f8ac2f98b4eca39eb2e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-iosx64-0.25.0-metadata.jar",
          "url": "resources-compose-iosx64-0.25.0-metadata.jar",
          "size": 14343,
          "sha512": "7fcbc02cb5fcccebc7a7fe5c143c5fe46a716c1dbab927b8fefdf35df0005a384bf100d70575528864875a81223b1d10c1644dfc976f77a5bf2a7ac66e7562db",
          "sha256": "0a897d31a3c5e55c75c39b460fff19b097e537ac1390e9864924adf74565ef03",
          "sha1": "54926e87334fbd584403727b2d47e7a7b5882137",
          "md5": "d96f31708f35b54f143a35f31792024c"
        }
      ]
    }
  ]
}
