{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources/0.25.0/resources-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources.klib",
          "url": "resources-iosarm64-0.25.0.klib",
          "size": 71818,
          "sha512": "2d1b3de38ad2a1d584207430d69786395fa86f8d533f77bbd882aa33915592c4eb7fd2286f9fd61aab80735426dd022ebaf44430ca56ccca9cdbcc36becc8cc8",
          "sha256": "1e2cfc49715a535da925c5e8eee96a79d900eb6b23cafa3441125c629121c905",
          "sha1": "3d313ace99b6e7ef0c11b1e0758673a4844a345e",
          "md5": "ef79f140609b78b70f5e28e731d028d6"
        },
        {
          "name": "resources-cinterop-bundleSearcher.klib",
          "url": "resources-iosarm64-0.25.0-cinterop-bundleSearcher.klib",
          "size": 26522,
          "sha512": "d41d9451680e6643508c8664ca6a28f4a19b4107942027dc44181b77c16d5ebf7c17c62082cc11d0bdde145031c62068cc73195dbdafa80c7ebae1e74c6a5c0a",
          "sha256": "914e37173450d22f02dd26100e9bb744700a09adceaaf6f88c65fd3c73c04322",
          "sha1": "03ec8c604d3467193e61c4b8c994402fed052c9f",
          "md5": "d44c2048e77c168f93d86eac00f7c6f5"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-iosarm64-0.25.0-sources.jar",
          "url": "resources-iosarm64-0.25.0-sources.jar",
          "size": 28454,
          "sha512": "d7a9480863a334eff6e2fb49e7ee0a62e119a6b0094d52b677d2cf01fcf98d85d1475f335a2f4fe3a57a950d1f1117b7725bf32a9a0208d3add53263ccb5e3a7",
          "sha256": "2ec7b352f8486154d900550840dc7a9ebd4ae41054d54e3640853f19a397c626",
          "sha1": "57a8fa13b870ab85d183c5071d220cfc15f5e5ed",
          "md5": "d58fbe7a8118d24ec551102465e49670"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-iosarm64-0.25.0-metadata.jar",
          "url": "resources-iosarm64-0.25.0-metadata.jar",
          "size": 39472,
          "sha512": "96a97f3d566e13127cd8f264b496ef2360b1281b193f4c254518889f49c973ea78ba44ae51d4546f45089e4a78fc830ef696081a8b224fc2aec77b6e14babef7",
          "sha256": "270484af890b3546c81851b9b0fc0a2b57fbb8deaf1637bb0c049091c08adceb",
          "sha1": "25c32ff377ba62a049e18f1993e8d66b0b824da2",
          "md5": "76c6c52d107544a3c60d9749ada33f03"
        }
      ]
    }
  ]
}
