{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-test/0.25.0/resources-test-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-test",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-js-0.25.0.klib",
          "url": "resources-test-js-0.25.0.klib",
          "size": 4832,
          "sha512": "8c2e5e1bb2236599a0c3829942e86b292dee803283131d962698b3f3f8f26f9311446bfdbac277e8d97dd7141bb66d40518d7ccc968bbeea6310848d3d42e72d",
          "sha256": "79d1b8240f93c3723bc837f08fdad842fd47b5825d51cffe6c9177f912aaeb0b",
          "sha1": "344ed5744a1fc70eb36e142021aeb1840c52a131",
          "md5": "f6e23577a693667257e673d3cd2f34d6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-js-0.25.0.klib",
          "url": "resources-test-js-0.25.0.klib",
          "size": 4832,
          "sha512": "8c2e5e1bb2236599a0c3829942e86b292dee803283131d962698b3f3f8f26f9311446bfdbac277e8d97dd7141bb66d40518d7ccc968bbeea6310848d3d42e72d",
          "sha256": "79d1b8240f93c3723bc837f08fdad842fd47b5825d51cffe6c9177f912aaeb0b",
          "sha1": "344ed5744a1fc70eb36e142021aeb1840c52a131",
          "md5": "f6e23577a693667257e673d3cd2f34d6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "resources-test-js-0.25.0-sources.jar",
          "url": "resources-test-js-0.25.0-sources.jar",
          "size": 2840,
          "sha512": "3ca2554dcf5526fabc62c647421021087eed36178a06564b8cd0081878ac701b0da8b5f4d2b28de1cd4e251cf2cdfcdad8be0d59803a1ece63098ac771976447",
          "sha256": "3075e6b3f72afe0511b96bae112b1723866eb561db4ff09149dcd92d17613278",
          "sha1": "986c3345421667002807eb86d98019df4723b591",
          "md5": "067753535f6a06b46f4a5d2a5b11416c"
        }
      ]
    }
  ]
}
