{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-test/0.25.0/resources-test-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-test",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test.klib",
          "url": "resources-test-macosx64-0.25.0.klib",
          "size": 7390,
          "sha512": "859b03500fe195198747fb868138fa53aa2ea4806fca055148c2b886063e9944471b3f64cffea242b9488ba6d475fab5bd7a2e927f7da8a9909ff198ad5017b0",
          "sha256": "d1d4b1d6dd79234612a563155df1b0b26984aa54d1d0b4f3a0ee29fbed40adb4",
          "sha1": "ea11cbe5c8df5a9dd865a967a7d788d1f34a5b71",
          "md5": "cda55dbf2aa6aaea7164a4a17e653758"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-test-macosx64-0.25.0-sources.jar",
          "url": "resources-test-macosx64-0.25.0-sources.jar",
          "size": 3838,
          "sha512": "a60e8fa0aaa54e7bdb16933dc1ac971b6f75e0c8f3d8fd093027a01df1a891a95a8388b4f5d48892eec9ac83733638434d89f96cb0d4cc5a0161c651735f0a9f",
          "sha256": "13d40d0e12f63d0c6f1eb5054b9ed7bdc7f8c3e68857984671fccb02fb6b71d9",
          "sha1": "b56e94779344ce9631e265a5771b6786c67d84ff",
          "md5": "88aa55f973347ec9b030e3cd588bff77"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-macosx64-0.25.0-metadata.jar",
          "url": "resources-test-macosx64-0.25.0-metadata.jar",
          "size": 12944,
          "sha512": "2009220b3c7e8420a1446ee6c8ce69af4443abe08577919cc25ac54469844286da3a016d7aff1124a0318d22731eee4b0303a2a17f31ad4d47255d98f01655db",
          "sha256": "7539fe6a88d32593c10f332acd25d13d2ae6272f484c53f6de2907493f49d2a5",
          "sha1": "18c8cc82fb6e54815affa58e6e8a724bb921fe96",
          "md5": "f671342c0e7a906ac76895481a409612"
        }
      ]
    }
  ]
}
