{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-compose/0.25.0/resources-compose-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-compose",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose.klib",
          "url": "resources-compose-macosx64-0.25.0.klib",
          "size": 25687,
          "sha512": "affe21173593483cae4f5edbf93521f3f83eaf26e46154edefc72b57f57d9bef44e0f435489e0cabdc9e995b30df79b25f1241f84deeff79b834a9bd35598029",
          "sha256": "03583237f4dd53744bf79a5af7d67e6402ceda48b3439c634c06fe9e4fcf9f86",
          "sha1": "717337095937b3f9d54d5f2a2ae4a48e8b82e986",
          "md5": "a6919e69984c8df3fa33e6368ea75b3c"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-compose-macosx64-0.25.0-sources.jar",
          "url": "resources-compose-macosx64-0.25.0-sources.jar",
          "size": 12092,
          "sha512": "eda884bb8cc173d9d5650ce532422f8b835735ba561b1e4a40697d63e7a97ba2f21793cdb028f9dee816801a5430a8d32949788909d8cd7f47e3db2e4f257dab",
          "sha256": "20e9b36eb51bba6032692f820a666ec79200e33ac9938dc56946e49d52592cf7",
          "sha1": "c4f8cb1d9a4e8796e5c2ca67d6dc201716d23842",
          "md5": "e6d04df6c3a7cbafd8aad6cbe59e7cce"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-macosx64-0.25.0-metadata.jar",
          "url": "resources-compose-macosx64-0.25.0-metadata.jar",
          "size": 14471,
          "sha512": "f804b5745668390612b785d40c61ab06c3088308bb06576f3e2061c4a18dbb99f925807cc217befe449fab02d53656c30d885d9451fe3b5e8615e578f1dce9e1",
          "sha256": "8fe4b7f3ec952dbfe567bd85a20b9414a6b67a426e3818ccd9a7e30d84d4f8a7",
          "sha1": "d44004e097f615d5f6e3dfafbab90b728e01ac95",
          "md5": "f6bd459f0999adc2956bdef90afb7a7b"
        }
      ]
    }
  ]
}
