{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-compose/0.25.0/resources-compose-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-compose",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-debug.aar",
          "url": "resources-compose-android-0.25.0-debug.aar",
          "size": 18530,
          "sha512": "3b733d564dd260eb1013c5137f1bb9d1b844381106716f247fd2590282761b1ad496da2b022a982de1632ca57d0fcd83e32afc37269049be11a3fcbf455e479b",
          "sha256": "eabf6707eabe09f26d83f3ee3bc7d3682c21a5de64daec973b42e32e0bd2618b",
          "sha1": "88c07a8b76d2951eff45255c8308c733cbb318e3",
          "md5": "aa4d3d7b2c7dddd797ccea9858450e99"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resources-compose-debug.aar",
          "url": "resources-compose-android-0.25.0-debug.aar",
          "size": 18530,
          "sha512": "3b733d564dd260eb1013c5137f1bb9d1b844381106716f247fd2590282761b1ad496da2b022a982de1632ca57d0fcd83e32afc37269049be11a3fcbf455e479b",
          "sha256": "eabf6707eabe09f26d83f3ee3bc7d3682c21a5de64daec973b42e32e0bd2618b",
          "sha1": "88c07a8b76d2951eff45255c8308c733cbb318e3",
          "md5": "aa4d3d7b2c7dddd797ccea9858450e99"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resources-compose-android-debug-0.25.0-sources.jar",
          "url": "resources-compose-android-0.25.0-debug-sources.jar",
          "size": 8856,
          "sha512": "b31db40f1d1cf7ef7849d699f9eeffad1a8f6cd9ddf8b3124258d0b3c1dc3d10874bc8cf42fb752e4ba2aa43cf95f4d7fab092735e04785fc59d57188b075f04",
          "sha256": "16e6345761d3a843bac442308ac90d0a17dad4ef63fc456c8a7c266799fdac8f",
          "sha1": "98275599ef043cf33b8ea905484cc4b31ec8a90a",
          "md5": "b8247d756a3fef3797c9828859e88970"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-release.aar",
          "url": "resources-compose-android-0.25.0.aar",
          "size": 17780,
          "sha512": "21ca19c6d4ce7f3f862ea586eb3b3c8bc862c9d3c665cc28a8c87a31c12043740a29e51717fbbc7e43d41e0aca6d9f67c808a5d15e52e02f4a50154a55ae0973",
          "sha256": "23157fb1916f06939999feebe51995b03d218a7ac15e214e7dff1303e22527ca",
          "sha1": "9f3b59ac67ee6e8ced29b1701228b9a95614b38c",
          "md5": "fe5b9912fd51a35c352dc0b0f79599fb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resources-compose-release.aar",
          "url": "resources-compose-android-0.25.0.aar",
          "size": 17780,
          "sha512": "21ca19c6d4ce7f3f862ea586eb3b3c8bc862c9d3c665cc28a8c87a31c12043740a29e51717fbbc7e43d41e0aca6d9f67c808a5d15e52e02f4a50154a55ae0973",
          "sha256": "23157fb1916f06939999feebe51995b03d218a7ac15e214e7dff1303e22527ca",
          "sha1": "9f3b59ac67ee6e8ced29b1701228b9a95614b38c",
          "md5": "fe5b9912fd51a35c352dc0b0f79599fb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resources-compose-android-0.25.0-sources.jar",
          "url": "resources-compose-android-0.25.0-sources.jar",
          "size": 8856,
          "sha512": "b31db40f1d1cf7ef7849d699f9eeffad1a8f6cd9ddf8b3124258d0b3c1dc3d10874bc8cf42fb752e4ba2aa43cf95f4d7fab092735e04785fc59d57188b075f04",
          "sha256": "16e6345761d3a843bac442308ac90d0a17dad4ef63fc456c8a7c266799fdac8f",
          "sha1": "98275599ef043cf33b8ea905484cc4b31ec8a90a",
          "md5": "b8247d756a3fef3797c9828859e88970"
        }
      ]
    }
  ]
}
