{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.icerock.moko",
    "module": "resources-test",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-metadata-0.25.0.jar",
          "url": "resources-test-0.25.0.jar",
          "size": 4536,
          "sha512": "da9af36f3790d83ab6dd6972ae3e7e2add13959bdaf5ade339a7f31aac4bedfa4736f682e21b9921bf1a36d7a15657de7cd22040c586ec458420fd2f4903ce62",
          "sha256": "2a3d479e0e3c5db56477cf1b091a85388723d31dc0bf5937c65df2b003b7a506",
          "sha1": "0ad9e5d9101ba266ffccb455992668dba5aab1a1",
          "md5": "ad9854908de4d68869c8c48b1fb1ae98"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resources-test-kotlin-0.25.0-sources.jar",
          "url": "resources-test-0.25.0-sources.jar",
          "size": 6174,
          "sha512": "cf57f93cb973c7b7a2bb68a559c5ceaae3e018180c9be8fd197aaf88c92cbed0745dd663c61a1ec4d61249a1412b43426e86869b31e191ca12c3e9a713a6f393",
          "sha256": "17caa5fc42006f38786194cf4ce38bfa6edad24bf0df9698464c863e87b83743",
          "sha1": "dbc1cb51d901962edf3ed7e37be0ae5b71824bce",
          "md5": "f5af3c754f43826390149f726a191c47"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-test-android/0.25.0/resources-test-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-test-android/0.25.0/resources-test-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-test-android/0.25.0/resources-test-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-test-android/0.25.0/resources-test-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-test-android/0.25.0/resources-test-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-test-android/0.25.0/resources-test-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iosarm64/0.25.0/resources-test-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iosarm64/0.25.0/resources-test-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iosarm64/0.25.0/resources-test-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iossimulatorarm64/0.25.0/resources-test-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iossimulatorarm64/0.25.0/resources-test-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iossimulatorarm64/0.25.0/resources-test-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iosx64/0.25.0/resources-test-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iosx64/0.25.0/resources-test-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-iosx64/0.25.0/resources-test-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-test-js/0.25.0/resources-test-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-test-js/0.25.0/resources-test-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-test-js/0.25.0/resources-test-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-test-jvm/0.25.0/resources-test-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-test-jvm/0.25.0/resources-test-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-test-jvm/0.25.0/resources-test-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-macosarm64/0.25.0/resources-test-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-macosarm64/0.25.0/resources-test-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-macosarm64/0.25.0/resources-test-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-macosx64/0.25.0/resources-test-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-macosx64/0.25.0/resources-test-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-macosx64/0.25.0/resources-test-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosarm32/0.25.0/resources-test-watchosarm32-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosarm32",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosarm32/0.25.0/resources-test-watchosarm32-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosarm32",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosarm32/0.25.0/resources-test-watchosarm32-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosarm32",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosarm64/0.25.0/resources-test-watchosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosarm64/0.25.0/resources-test-watchosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosarm64/0.25.0/resources-test-watchosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchossimulatorarm64/0.25.0/resources-test-watchossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchossimulatorarm64/0.25.0/resources-test-watchossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchossimulatorarm64/0.25.0/resources-test-watchossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosx64/0.25.0/resources-test-watchosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosx64/0.25.0/resources-test-watchosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-test-watchosx64/0.25.0/resources-test-watchosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-test-watchosx64",
        "version": "0.25.0"
      }
    }
  ]
}
