{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources/0.25.0/resources-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources.klib",
          "url": "resources-iossimulatorarm64-0.25.0.klib",
          "size": 71904,
          "sha512": "3936e8a8f9e50c2c429934b336b220a84663bc3557829f14bbe497b7e418ef9d8ea2c82d1947d8ba326e23b6e5cb38f6a8782f22f264fdd31b91508deacc52b9",
          "sha256": "732defbdad5d27164d3a17a0221d7e66ee69bf565b86a12778e35e52cdbc92a9",
          "sha1": "4da2c8a18efb19fae16a4ae5ced96303ce11911a",
          "md5": "2e0a8ace19b220dfdd33ec5891a7305a"
        },
        {
          "name": "resources-cinterop-bundleSearcher.klib",
          "url": "resources-iossimulatorarm64-0.25.0-cinterop-bundleSearcher.klib",
          "size": 26733,
          "sha512": "0f6f232782e4bec7cf0f16843b8ce02972a18703df5fc68130b891594e76a33d0e19d390860fa7179f665e81568cd37344d742bb5cc7f708e27739aa5561b194",
          "sha256": "fe48e6a911896c720266cecc55ea715dd0578993533f640b9f930128a3d3ee60",
          "sha1": "ea0e039c49eca8f24d91b25d7bdd32831b637ca6",
          "md5": "0c849c1d13e10cdc6de883c46a1683d9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "resources-iossimulatorarm64-0.25.0-sources.jar",
          "url": "resources-iossimulatorarm64-0.25.0-sources.jar",
          "size": 28454,
          "sha512": "d7a9480863a334eff6e2fb49e7ee0a62e119a6b0094d52b677d2cf01fcf98d85d1475f335a2f4fe3a57a950d1f1117b7725bf32a9a0208d3add53263ccb5e3a7",
          "sha256": "2ec7b352f8486154d900550840dc7a9ebd4ae41054d54e3640853f19a397c626",
          "sha1": "57a8fa13b870ab85d183c5071d220cfc15f5e5ed",
          "md5": "d58fbe7a8118d24ec551102465e49670"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-iossimulatorarm64-0.25.0-metadata.jar",
          "url": "resources-iossimulatorarm64-0.25.0-metadata.jar",
          "size": 39472,
          "sha512": "96a97f3d566e13127cd8f264b496ef2360b1281b193f4c254518889f49c973ea78ba44ae51d4546f45089e4a78fc830ef696081a8b224fc2aec77b6e14babef7",
          "sha256": "270484af890b3546c81851b9b0fc0a2b57fbb8deaf1637bb0c049091c08adceb",
          "sha1": "25c32ff377ba62a049e18f1993e8d66b0b824da2",
          "md5": "76c6c52d107544a3c60d9749ada33f03"
        }
      ]
    }
  ]
}
