{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.icerock.moko",
    "module": "resources-compose",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-compose-metadata-0.25.0.jar",
          "url": "resources-compose-0.25.0.jar",
          "size": 5015,
          "sha512": "f613be75d91d291ef5a25672035cdb0e4f61fd6148c70020f3426647177f46b33f8f21551f0a98aa826172e4ca7d73c68b6ecb022cd76dedd4ee64030974c725",
          "sha256": "5fa59735eb155cc740183c5e2628b75bd7b74631cd9b94cd2672557f99d6cb3c",
          "sha1": "04ffbf1f398acb64089fdbf0a7bcaa6fba60b8c8",
          "md5": "2714392a2ff416ea39c3e05ebfbf8a8f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "resources-compose-kotlin-0.25.0-sources.jar",
          "url": "resources-compose-0.25.0-sources.jar",
          "size": 14890,
          "sha512": "c4cb40f8fdf36feb2654e34abb026bd92a5f33b75b195cdb4d43b966d965e67c010908b40e684666c83057d4a122de525d216a2ab62a69e4c5726a2fbaac121c",
          "sha256": "1cb548f62e728a4c6fdc3dc82263de3774d67c6084f3bbbf55c54604b9ab3c21",
          "sha1": "803e1c521e5a045fcfa53da7a317e4ec6a334e58",
          "md5": "8335b6b021a08dae3f7b3c373e288b84"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-compose-android/0.25.0/resources-compose-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-compose-android/0.25.0/resources-compose-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-compose-android/0.25.0/resources-compose-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-compose-android/0.25.0/resources-compose-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-compose-android/0.25.0/resources-compose-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../resources-compose-android/0.25.0/resources-compose-android-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-android",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iosarm64/0.25.0/resources-compose-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iosarm64/0.25.0/resources-compose-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iosarm64/0.25.0/resources-compose-iosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iossimulatorarm64/0.25.0/resources-compose-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iossimulatorarm64/0.25.0/resources-compose-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iossimulatorarm64/0.25.0/resources-compose-iossimulatorarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iossimulatorarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iosx64/0.25.0/resources-compose-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iosx64/0.25.0/resources-compose-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-iosx64/0.25.0/resources-compose-iosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-iosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-compose-js/0.25.0/resources-compose-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-compose-js/0.25.0/resources-compose-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../resources-compose-js/0.25.0/resources-compose-js-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-js",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-compose-jvm/0.25.0/resources-compose-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-compose-jvm/0.25.0/resources-compose-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../resources-compose-jvm/0.25.0/resources-compose-jvm-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-jvm",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-macosarm64/0.25.0/resources-compose-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-macosarm64/0.25.0/resources-compose-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-macosarm64/0.25.0/resources-compose-macosarm64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-macosarm64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-macosx64/0.25.0/resources-compose-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-macosx64/0.25.0/resources-compose-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-macosx64",
        "version": "0.25.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../resources-compose-macosx64/0.25.0/resources-compose-macosx64-0.25.0.module",
        "group": "dev.icerock.moko",
        "module": "resources-compose-macosx64",
        "version": "0.25.0"
      }
    }
  ]
}
