{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.icerock.moko",
    "module": "resources-generator",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-generator-0.25.0.jar",
          "url": "resources-generator-0.25.0.jar",
          "size": 707522,
          "sha512": "f6a6d4a3737719f72b93ab69e7e5724d0a7a07915526eed2fa7a643f2024d1faa7db26290053af8fd3c9c65e440d164afd0367255baaafe6fe79f062258ebbb0",
          "sha256": "ef21dbf9cc80abebfd7fdd2b8ef9a7b82de0185abcd5713ebe25fbcd2915b2cc",
          "sha1": "566cf26f3532ca968b891fa0bc7f4fdbbd61bb5f",
          "md5": "cbc3fe0dcdb21b05a5f16cdbd0207ab2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-generator-0.25.0.jar",
          "url": "resources-generator-0.25.0.jar",
          "size": 707522,
          "sha512": "f6a6d4a3737719f72b93ab69e7e5724d0a7a07915526eed2fa7a643f2024d1faa7db26290053af8fd3c9c65e440d164afd0367255baaafe6fe79f062258ebbb0",
          "sha256": "ef21dbf9cc80abebfd7fdd2b8ef9a7b82de0185abcd5713ebe25fbcd2915b2cc",
          "sha1": "566cf26f3532ca968b891fa0bc7f4fdbbd61bb5f",
          "md5": "cbc3fe0dcdb21b05a5f16cdbd0207ab2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resources-generator-0.25.0-javadoc.jar",
          "url": "resources-generator-0.25.0-javadoc.jar",
          "size": 261,
          "sha512": "c93f1bcb38bcf190949a7a206a2af0ed168b67e1308243e9e5bd744210f18bf9a530251b0038e58b78686ea252c6a2ef3d8410bc7683adf664c2240fc8d7b849",
          "sha256": "77b5bcd4750569f9ac65b2506ff7ceaada8360172fda8fccbce37c2979609a0e",
          "sha1": "ac69518e11995f17acfffe67071bae4cfbf5c319",
          "md5": "956f58340b6c11ee5acbb292f32a9783"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "resources-generator-0.25.0-sources.jar",
          "url": "resources-generator-0.25.0-sources.jar",
          "size": 110162,
          "sha512": "6530e015caed532cf4de82b7188cf1a47cadfb80c3f6237bfbf3e9cdc5ee5c7082daf2bb472c496c7aed6e5ef23bd6fda719da0fcb53bc45a53afaf2bce6e190",
          "sha256": "4c0083366c51c42eb33bfabcb45da9f7c9246bf306d1cd5026d07c6b84ca93e0",
          "sha1": "b442f22e60f1174caef07ce2b406b47c82a345dc",
          "md5": "b1787dc5c56db715afcb16b1a4dc3e90"
        }
      ]
    }
  ]
}
