{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-test/0.25.0/resources-test-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-test",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-jvm-0.25.0.jar",
          "url": "resources-test-jvm-0.25.0.jar",
          "size": 2081,
          "sha512": "134c1bbe47cb3f30fb1c529348b39212ecf329ffa4a43964c40ffd6f29688e5a80ee7ffa8f61f211d2cbcd9c8df1c1e8951cdbd2504a219c1b1b9293f7cfa76e",
          "sha256": "3aed4ea6428fd85eee334a88c6085896c31fe7f587f40335d87ead92fa898a29",
          "sha1": "f617369e3f32e75ecf4f21cb0370920b971e0e8f",
          "md5": "2d295f52ff50db9ae983ae176b646bba"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-jvm-0.25.0.jar",
          "url": "resources-test-jvm-0.25.0.jar",
          "size": 2081,
          "sha512": "134c1bbe47cb3f30fb1c529348b39212ecf329ffa4a43964c40ffd6f29688e5a80ee7ffa8f61f211d2cbcd9c8df1c1e8951cdbd2504a219c1b1b9293f7cfa76e",
          "sha256": "3aed4ea6428fd85eee334a88c6085896c31fe7f587f40335d87ead92fa898a29",
          "sha1": "f617369e3f32e75ecf4f21cb0370920b971e0e8f",
          "md5": "2d295f52ff50db9ae983ae176b646bba"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "resources-test-jvm-0.25.0-sources.jar",
          "url": "resources-test-jvm-0.25.0-sources.jar",
          "size": 2001,
          "sha512": "6cc659e5226c226f59d7269732063dc2be17058416e171dd17070bca004c4d787d94bad265cdda8ced6fadb85064d27c135d828f23d6c6b10bc6403d77141fa3",
          "sha256": "ade2d5a42782a502159c134d768717912faace166dd411244b7ff7e206b1459e",
          "sha1": "c391f34473b521c13be97716d8b59a06afb634c6",
          "md5": "544b78a910606cf89a466f90771dfd43"
        }
      ]
    }
  ]
}
