{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources/0.25.0/resources-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-js-0.25.0.klib",
          "url": "resources-js-0.25.0.klib",
          "size": 88813,
          "sha512": "f194fa286875ab489e8af626ad6defccfe2d48245a95fed096de55886be33a6d5889abefbe4fe53cdcffc628dc4fc59c540eb0360f8f4d761d1602f3a4b31c1a",
          "sha256": "fb1bc4e91daed27a0e2fbfed654a78bbe4ad7c3e210f600bc5fbe41f762cbc26",
          "sha1": "af30967c81fa8c05710988bc244888ccb323a612",
          "md5": "21d2c7b39d1940f05f9845ff02d1b114"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "graphics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "resources-js-0.25.0.klib",
          "url": "resources-js-0.25.0.klib",
          "size": 88813,
          "sha512": "f194fa286875ab489e8af626ad6defccfe2d48245a95fed096de55886be33a6d5889abefbe4fe53cdcffc628dc4fc59c540eb0360f8f4d761d1602f3a4b31c1a",
          "sha256": "fb1bc4e91daed27a0e2fbfed654a78bbe4ad7c3e210f600bc5fbe41f762cbc26",
          "sha1": "af30967c81fa8c05710988bc244888ccb323a612",
          "md5": "21d2c7b39d1940f05f9845ff02d1b114"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "resources-js-0.25.0-sources.jar",
          "url": "resources-js-0.25.0-sources.jar",
          "size": 29257,
          "sha512": "0901aa8a14310d23219107e0e4b7eb8f5c6423fc6a8d72c6f78d81427c545855f3a4e72974887f0cd7f8502242f8c7b9246b1318d710a84121a4f542c0cb97e9",
          "sha256": "37676f9972369d58f4838ef4c2e0469ef26dd115fb1604be0122b87d71b7197d",
          "sha1": "9451d5592928c4307f5704e9f2467c39b5ed1f5b",
          "md5": "883e7f6efae681ebabe00ebcdd4402ec"
        }
      ]
    }
  ]
}
