{
  "formatVersion": "1.1",
  "component": {
    "url": "../../resources-test/0.25.0/resources-test-0.25.0.module",
    "group": "dev.icerock.moko",
    "module": "resources-test",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-debug.aar",
          "url": "resources-test-android-0.25.0-debug.aar",
          "size": 1785,
          "sha512": "e4c959d0da41dbfedf617710120b28a25c29d2597569509f3a7e126776e24708fde5befa6b768f5c040f6cf58c18e3b79bf73fd2c0fa0d3553f3dc9fa6499dae",
          "sha256": "e1028ca2d29702e2aa585be639bcc0ef1092ae70b9eaebdfd527dd7b0230facd",
          "sha1": "308af4252168f256b2086b1d7c7405200c7d857d",
          "md5": "1620d098bd348b0a1a0f246ebb0cd932"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resources-test-debug.aar",
          "url": "resources-test-android-0.25.0-debug.aar",
          "size": 1785,
          "sha512": "e4c959d0da41dbfedf617710120b28a25c29d2597569509f3a7e126776e24708fde5befa6b768f5c040f6cf58c18e3b79bf73fd2c0fa0d3553f3dc9fa6499dae",
          "sha256": "e1028ca2d29702e2aa585be639bcc0ef1092ae70b9eaebdfd527dd7b0230facd",
          "sha1": "308af4252168f256b2086b1d7c7405200c7d857d",
          "md5": "1620d098bd348b0a1a0f246ebb0cd932"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resources-test-android-debug-0.25.0-sources.jar",
          "url": "resources-test-android-0.25.0-debug-sources.jar",
          "size": 2723,
          "sha512": "6e84d6def26815181859998ffbfc9a5ff01a764bda30ecf77e780e156248f0e26ba69552bec056a74c8381a6ac532ef4171b6b3e9d5319ee84ef3627d1bed489",
          "sha256": "c00a124a4fd037ec56128ba147b3c4b927c59ca84370491ca25a3f496a27d782",
          "sha1": "eafa67aef3c188e4a1fdf92c1d8d70ea6302b58e",
          "md5": "b4f21c0ae69e87fc162cab9db83925a7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "resources-test-release.aar",
          "url": "resources-test-android-0.25.0.aar",
          "size": 1756,
          "sha512": "a37013ce65a356aa2ac3c304039d92d09b7613ac8db5ab7f47bc8cda446516e25bf816534bcde5624f073efd4ef997177dc9377052d4739cac8b03e2841ba4c6",
          "sha256": "43c8a67bbaa727cbe9a5dd9b5be300f168b8bc695181a3b5904d2c433c61b979",
          "sha1": "3bd7352d4a85c40144059aa1808198031939deda",
          "md5": "fdfc158352579a673c1b6bcf4ce6f151"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "dev.icerock.moko",
          "module": "resources",
          "version": {
            "requires": "0.25.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "resources-test-release.aar",
          "url": "resources-test-android-0.25.0.aar",
          "size": 1756,
          "sha512": "a37013ce65a356aa2ac3c304039d92d09b7613ac8db5ab7f47bc8cda446516e25bf816534bcde5624f073efd4ef997177dc9377052d4739cac8b03e2841ba4c6",
          "sha256": "43c8a67bbaa727cbe9a5dd9b5be300f168b8bc695181a3b5904d2c433c61b979",
          "sha1": "3bd7352d4a85c40144059aa1808198031939deda",
          "md5": "fdfc158352579a673c1b6bcf4ce6f151"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "resources-test-android-0.25.0-sources.jar",
          "url": "resources-test-android-0.25.0-sources.jar",
          "size": 2723,
          "sha512": "6e84d6def26815181859998ffbfc9a5ff01a764bda30ecf77e780e156248f0e26ba69552bec056a74c8381a6ac532ef4171b6b3e9d5319ee84ef3627d1bed489",
          "sha256": "c00a124a4fd037ec56128ba147b3c4b927c59ca84370491ca25a3f496a27d782",
          "sha1": "eafa67aef3c188e4a1fdf92c1d8d70ea6302b58e",
          "md5": "b4f21c0ae69e87fc162cab9db83925a7"
        }
      ]
    }
  ]
}
